travis:
  secure:
    BINSTAR_TOKEN: oPgFyl5sswP4Vi9+g8UaWQ2POcCzURZJVhT511yLEChXPpCYNgBo6DLDUlVNOJ6Uogo+KRqyDc+iWXjZ9EjflpfsXhTsKWoaFhuS93LOOarOAClUquvzRTf7+EjsQ3GSJBHZ5Sd33SbMeMWL10pj5/5lP7tPsco9C3LKVCsUB/KqzL+enZXxWIq/P2UMl6d1V7wT5kgYlgt945IAtQafzrL/Syg0lCOdFKTnX3V4+0+Mi3Qj6EdPbJLMZH0F+/dmdYUIsknzHAyRl/QlvfKixF07u2E/5gJS7NtkjZyAnAyoKVm3rjREdnal5d4kZYQ7ZuxFtbGueVa4RCI4i+w0xnUu9p1N+cRO4AJD+xJUQ0o1t2Y54f6v3rttBmKZKptgiRnGgjcpN/1aznvfw86CD6O81T0cgMqlL+wc50vxt7YhFeo45ruNdYSXdHvAgrBz/VlxrfvAmnaw21dsfWJL6MODhyA1w2t+kWs4aTg/XgaoV329tQpkpjXJ1ucQBi/Evaf9qiQvRoIEdzIMzltbrPTmSZud0dFwzCApKJXnG3dnhBDGzCoHtQ5U2ckstanvjtm7N/cQ0qfF0PiRYLuW5ElQMkarmhttoVPRQDRLZyLsofE0WugNshs+fm3hV1Pxts6ZGLr5o4I4TC3UJ3zfBqx8utgq3T/p3f+sYt2nLkc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
